// ======================================================================
// \title  PacketTransferPortAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for PacketTransfer port
// ======================================================================

#ifndef OBC_project_PacketTransferPortAc_HPP
#define OBC_project_PacketTransferPortAc_HPP

#include <cstdio>
#include <cstring>

#include "DataPacket/DataPacketSerializableAc.hpp"
#include "FpConfig.hpp"
#include "Fw/Comp/PassiveComponentBase.hpp"
#include "Fw/Port/InputPortBase.hpp"
#include "Fw/Port/OutputPortBase.hpp"
#include "Fw/Types/Serializable.hpp"
#include "Fw/Types/StringType.hpp"

namespace OBC_project {

  //! Input PacketTransfer port
  //! Port for requesting packet transfer
  class InputPacketTransferPort :
    public Fw::InputPortBase
  {

    public:

      // ----------------------------------------------------------------------
      // Constants
      // ----------------------------------------------------------------------

      enum {
        //! The size of the serial representations of the port arguments
        SERIALIZED_SIZE =
          OBC_project::DataPacket::SERIALIZED_SIZE
      };

    public:

      // ----------------------------------------------------------------------
      // Types
      // ----------------------------------------------------------------------

      //! The port callback function type
      typedef void (*CompFuncPtr)(
        Fw::PassiveComponentBase* callComp,
        NATIVE_INT_TYPE portNum,
        const OBC_project::DataPacket& packet
      );

    public:

      // ----------------------------------------------------------------------
      // Input Port Member functions
      // ----------------------------------------------------------------------

      //! Constructor
      InputPacketTransferPort();

      //! Initialization function
      void init();

      //! Register a component
      void addCallComp(
          Fw::PassiveComponentBase* callComp, //!< The containing component
          CompFuncPtr funcPtr //!< The port callback function
      );

      //! Invoke a port interface
      void invoke(const OBC_project::DataPacket& packet);

    private:

#if FW_PORT_SERIALIZATION == 1

      //! Invoke the port with serialized arguments
      Fw::SerializeStatus invokeSerial(Fw::SerializeBufferBase& _buffer);

#endif

    private:

      // ----------------------------------------------------------------------
      // Member variables
      // ----------------------------------------------------------------------

      //! The pointer to the port callback function
      CompFuncPtr m_func;

  };

  //! Output PacketTransfer port
  //! Port for requesting packet transfer
  class OutputPacketTransferPort :
    public Fw::OutputPortBase
  {

    public:

      // ----------------------------------------------------------------------
      // Output Port Member functions
      // ----------------------------------------------------------------------

      //! Constructor
      OutputPacketTransferPort();

      //! Initialization function
      void init();

      //! Register an input port
      void addCallPort(
          InputPacketTransferPort* callPort //!< The input port
      );

      //! Invoke a port interface
      void invoke(const OBC_project::DataPacket& packet);

    private:

      // ----------------------------------------------------------------------
      // Member variables
      // ----------------------------------------------------------------------

      //! The pointer to the input port
      InputPacketTransferPort* m_port;

  };

}

#endif
