// ======================================================================
// \title  PacketTransferPortAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for PacketTransfer port
// ======================================================================

#include "AdapterPorts/PacketTransferPortAc.hpp"
#include "Fw/Types/Assert.hpp"
#include "Fw/Types/StringUtils.hpp"

namespace OBC_project {

  namespace {

    // ----------------------------------------------------------------------
    // Port buffer class
    // ----------------------------------------------------------------------

    class PacketTransferPortBuffer : public Fw::SerializeBufferBase {

      public:

        NATIVE_UINT_TYPE getBuffCapacity() const {
          return InputPacketTransferPort::SERIALIZED_SIZE;
        }

        U8* getBuffAddr() {
          return m_buff;
        }

        const U8* getBuffAddr() const {
          return m_buff;
        }

      private:

        U8 m_buff[InputPacketTransferPort::SERIALIZED_SIZE];

    };

  }

  // ----------------------------------------------------------------------
  // Input Port Member functions
  // ----------------------------------------------------------------------

  InputPacketTransferPort ::
    InputPacketTransferPort() :
      Fw::InputPortBase(),
      m_func(nullptr)
  {

  }

  void InputPacketTransferPort ::
    init()
  {
    Fw::InputPortBase::init();
  }

  void InputPacketTransferPort ::
    addCallComp(
        Fw::PassiveComponentBase* callComp,
        CompFuncPtr funcPtr
    )
  {
    FW_ASSERT(callComp != nullptr);
    FW_ASSERT(funcPtr != nullptr);

    this->m_comp = callComp;
    this->m_func = funcPtr;
    this->m_connObj = callComp;
  }

  void InputPacketTransferPort ::
    invoke(const OBC_project::DataPacket& packet)
  {
#if FW_PORT_TRACING == 1
    this->trace();
#endif

    FW_ASSERT(this->m_comp != nullptr);
    FW_ASSERT(this->m_func != nullptr);

    return this->m_func(this->m_comp, this->m_portNum, packet);
  }

#if FW_PORT_SERIALIZATION == 1

  Fw::SerializeStatus InputPacketTransferPort ::
    invokeSerial(Fw::SerializeBufferBase& _buffer)
  {
    Fw::SerializeStatus _status;

#if FW_PORT_SERIALIZATION == 1
    this->trace();
#endif

    FW_ASSERT(this->m_comp != nullptr);
    FW_ASSERT(this->m_func != nullptr);

    OBC_project::DataPacket packet;
    _status = _buffer.deserialize(packet);
    if (_status != Fw::FW_SERIALIZE_OK) {
      return _status;
    }

    this->m_func(this->m_comp, this->m_portNum, packet);

    return Fw::FW_SERIALIZE_OK;
  }

#endif

  // ----------------------------------------------------------------------
  // Output Port Member functions
  // ----------------------------------------------------------------------

  OutputPacketTransferPort ::
    OutputPacketTransferPort() :
      Fw::OutputPortBase(),
      m_port(nullptr)
  {

  }

  void OutputPacketTransferPort ::
    init()
  {
    Fw::OutputPortBase::init();
  }

  void OutputPacketTransferPort ::
    addCallPort(InputPacketTransferPort* callPort)
  {
    FW_ASSERT(callPort != nullptr);

    this->m_port = callPort;
    this->m_connObj = callPort;

#if FW_PORT_SERIALIZATION == 1
    this->m_serPort = nullptr;
#endif
  }

  void OutputPacketTransferPort ::
    invoke(const OBC_project::DataPacket& packet)
  {
#if FW_PORT_TRACING == 1
    this->trace();
#endif

#if FW_PORT_SERIALIZATION
    FW_ASSERT((this->m_port != nullptr) || (this->m_serPort != nullptr));

    if (this->m_port != nullptr) {
      this->m_port->invoke(packet);
    }
    else {
      Fw::SerializeStatus _status;
      PacketTransferPortBuffer _buffer;

      _status = _buffer.serialize(packet);
      FW_ASSERT(_status == Fw::FW_SERIALIZE_OK, static_cast<FwAssertArgType>(_status));

      _status = this->m_serPort->invokeSerial(_buffer);
      FW_ASSERT(_status == Fw::FW_SERIALIZE_OK, static_cast<FwAssertArgType>(_status));
    }
#else
    FW_ASSERT(this->m_port != nullptr);
    this->m_port->invoke(packet);
#endif
  }

}
