// ======================================================================
// \title  PacketTransferResultPortAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for PacketTransferResult port
// ======================================================================

#include "AdapterPorts/PacketTransferResultPortAc.hpp"
#include "Fw/Types/Assert.hpp"
#include "Fw/Types/StringUtils.hpp"

namespace OBC_project {

  namespace {

    // ----------------------------------------------------------------------
    // Port buffer class
    // ----------------------------------------------------------------------

    class PacketTransferResultPortBuffer : public Fw::SerializeBufferBase {

      public:

        NATIVE_UINT_TYPE getBuffCapacity() const {
          return InputPacketTransferResultPort::SERIALIZED_SIZE;
        }

        U8* getBuffAddr() {
          return m_buff;
        }

        const U8* getBuffAddr() const {
          return m_buff;
        }

      private:

        U8 m_buff[InputPacketTransferResultPort::SERIALIZED_SIZE];

    };

  }

  // ----------------------------------------------------------------------
  // Input Port Member functions
  // ----------------------------------------------------------------------

  InputPacketTransferResultPort ::
    InputPacketTransferResultPort() :
      Fw::InputPortBase(),
      m_func(nullptr)
  {

  }

  void InputPacketTransferResultPort ::
    init()
  {
    Fw::InputPortBase::init();
  }

  void InputPacketTransferResultPort ::
    addCallComp(
        Fw::PassiveComponentBase* callComp,
        CompFuncPtr funcPtr
    )
  {
    FW_ASSERT(callComp != nullptr);
    FW_ASSERT(funcPtr != nullptr);

    this->m_comp = callComp;
    this->m_func = funcPtr;
    this->m_connObj = callComp;
  }

  void InputPacketTransferResultPort ::
    invoke(U32 result)
  {
#if FW_PORT_TRACING == 1
    this->trace();
#endif

    FW_ASSERT(this->m_comp != nullptr);
    FW_ASSERT(this->m_func != nullptr);

    return this->m_func(this->m_comp, this->m_portNum, result);
  }

#if FW_PORT_SERIALIZATION == 1

  Fw::SerializeStatus InputPacketTransferResultPort ::
    invokeSerial(Fw::SerializeBufferBase& _buffer)
  {
    Fw::SerializeStatus _status;

#if FW_PORT_SERIALIZATION == 1
    this->trace();
#endif

    FW_ASSERT(this->m_comp != nullptr);
    FW_ASSERT(this->m_func != nullptr);

    U32 result;
    _status = _buffer.deserialize(result);
    if (_status != Fw::FW_SERIALIZE_OK) {
      return _status;
    }

    this->m_func(this->m_comp, this->m_portNum, result);

    return Fw::FW_SERIALIZE_OK;
  }

#endif

  // ----------------------------------------------------------------------
  // Output Port Member functions
  // ----------------------------------------------------------------------

  OutputPacketTransferResultPort ::
    OutputPacketTransferResultPort() :
      Fw::OutputPortBase(),
      m_port(nullptr)
  {

  }

  void OutputPacketTransferResultPort ::
    init()
  {
    Fw::OutputPortBase::init();
  }

  void OutputPacketTransferResultPort ::
    addCallPort(InputPacketTransferResultPort* callPort)
  {
    FW_ASSERT(callPort != nullptr);

    this->m_port = callPort;
    this->m_connObj = callPort;

#if FW_PORT_SERIALIZATION == 1
    this->m_serPort = nullptr;
#endif
  }

  void OutputPacketTransferResultPort ::
    invoke(U32 result)
  {
#if FW_PORT_TRACING == 1
    this->trace();
#endif

#if FW_PORT_SERIALIZATION
    FW_ASSERT((this->m_port != nullptr) || (this->m_serPort != nullptr));

    if (this->m_port != nullptr) {
      this->m_port->invoke(result);
    }
    else {
      Fw::SerializeStatus _status;
      PacketTransferResultPortBuffer _buffer;

      _status = _buffer.serialize(result);
      FW_ASSERT(_status == Fw::FW_SERIALIZE_OK, static_cast<FwAssertArgType>(_status));

      _status = this->m_serPort->invokeSerial(_buffer);
      FW_ASSERT(_status == Fw::FW_SERIALIZE_OK, static_cast<FwAssertArgType>(_status));
    }
#else
    FW_ASSERT(this->m_port != nullptr);
    this->m_port->invoke(result);
#endif
  }

}
